os:
  - linux
sudo: false
addons:
  apt:
    # Flutter depends on /usr/lib/x86_64-linux-gnu/libstdc++.so.6 version GLIBCXX_3.4.18
    sources:
      - ubuntu-toolchain-r-test # if we don't specify this, the libstdc++6 we get is the wrong version
    packages:
      - libstdc++6
      - fonts-droid-fallback
before_script:
  - git clone https://github.com/flutter/flutter.git -b stable
  - ./flutter/bin/flutter doctor
cache:
  directories:
    - $HOME/.pub-cache

jobs:
  include:
    - stage: Tests
      name: Unit tests
      script:
        - ./flutter/bin/flutter test
    - name: Analyze
      script:
        - ./flutter/bin/flutter clean
        - ./flutter/bin/flutter pub run build_runner build --enable-experiment non-nullable
        - ./flutter/bin/flutter analyze
    - name: Build
      script:
        - ./flutter/bin/flutter build aot
        - ./flutter/bin/flutter build bundle